# capitalize()
# count()
# upper()
# lower()
# title()
# swapcase()
# index()
s=input()
print(s.capitalize())
print(s.title())
print(s.upper())
print(s.lower())
print(s.count(input()))
print(s.find(input()))
print(s.index(input()))